export type SurahMeta = {
  number: number;
  arabic: string;
  transliteration: string;
  russian: string;
  ayahs: number;
  type: 'meccan' | 'medinan';
};

export const SURAHS: SurahMeta[] = [
  { number: 1, arabic: 'الفاتحة', transliteration: 'Аль-Фатиха', russian: 'Открывающая', ayahs: 7, type: 'meccan' },
  { number: 2, arabic: 'البقرة', transliteration: 'Аль-Бакара', russian: 'Корова', ayahs: 286, type: 'medinan' },
  { number: 3, arabic: 'آل عمران', transliteration: 'Аль Имран', russian: 'Семейство Имрана', ayahs: 200, type: 'medinan' },
  { number: 4, arabic: 'النساء', transliteration: 'Ан-Ниса', russian: 'Женщины', ayahs: 176, type: 'medinan' },
  { number: 5, arabic: 'المائدة', transliteration: 'Аль-Маида', russian: 'Трапеза', ayahs: 120, type: 'medinan' },
  { number: 6, arabic: 'الأنعام', transliteration: 'Аль-Анам', russian: 'Скот', ayahs: 165, type: 'meccan' },
  { number: 7, arabic: 'الأعراف', transliteration: 'Аль-Аараф', russian: 'Преграды', ayahs: 206, type: 'meccan' },
  { number: 8, arabic: 'الأنفال', transliteration: 'Аль-Анфаль', russian: 'Добыча', ayahs: 75, type: 'medinan' },
  { number: 9, arabic: 'التوبة', transliteration: 'Ат-Тауба', russian: 'Покаяние', ayahs: 129, type: 'medinan' },
  { number: 10, arabic: 'يونس', transliteration: 'Йунус', russian: 'Юнус', ayahs: 109, type: 'meccan' },
  { number: 11, arabic: 'هود', transliteration: 'Худ', russian: 'Худ', ayahs: 123, type: 'meccan' },
  { number: 12, arabic: 'يوسف', transliteration: 'Йусуф', russian: 'Юсуф', ayahs: 111, type: 'meccan' },
  { number: 13, arabic: 'الرعد', transliteration: 'Ар-Раад', russian: 'Гром', ayahs: 43, type: 'medinan' },
  { number: 14, arabic: 'إبراهيم', transliteration: 'Ибрахим', russian: 'Ибрахим', ayahs: 52, type: 'meccan' },
  { number: 15, arabic: 'الحجر', transliteration: 'Аль-Хиджр', russian: 'Аль-Хиджр', ayahs: 99, type: 'meccan' },
  { number: 16, arabic: 'النحل', transliteration: 'Ан-Нахль', russian: 'Пчёлы', ayahs: 128, type: 'meccan' },
  { number: 17, arabic: 'الإسراء', transliteration: 'Аль-Исра', russian: 'Ночной перенос', ayahs: 111, type: 'meccan' },
  { number: 18, arabic: 'الكهف', transliteration: 'Аль-Кахф', russian: 'Пещера', ayahs: 110, type: 'meccan' },
  { number: 19, arabic: 'مريم', transliteration: 'Марьям', russian: 'Мария', ayahs: 98, type: 'meccan' },
  { number: 20, arabic: 'طه', transliteration: 'Та Ха', russian: 'Та Ха', ayahs: 135, type: 'meccan' },
  { number: 21, arabic: 'الأنبياء', transliteration: 'Аль-Анбийа', russian: 'Пророки', ayahs: 112, type: 'meccan' },
  { number: 22, arabic: 'الحج', transliteration: 'Аль-Хадж', russian: 'Паломничество', ayahs: 78, type: 'medinan' },
  { number: 23, arabic: 'المؤمنون', transliteration: 'Аль-Муминун', russian: 'Верующие', ayahs: 118, type: 'meccan' },
  { number: 24, arabic: 'النور', transliteration: 'Ан-Нур', russian: 'Свет', ayahs: 64, type: 'medinan' },
  { number: 25, arabic: 'الفرقان', transliteration: 'Аль-Фуркан', russian: 'Различение', ayahs: 77, type: 'meccan' },
  { number: 26, arabic: 'الشعراء', transliteration: 'Аш-Шуара', russian: 'Поэты', ayahs: 227, type: 'meccan' },
  { number: 27, arabic: 'النمل', transliteration: 'Ан-Намль', russian: 'Муравьи', ayahs: 93, type: 'meccan' },
  { number: 28, arabic: 'القصص', transliteration: 'Аль-Касас', russian: 'Рассказы', ayahs: 88, type: 'meccan' },
  { number: 29, arabic: 'العنكبوت', transliteration: 'Аль-Анкабут', russian: 'Паук', ayahs: 69, type: 'meccan' },
  { number: 30, arabic: 'الروم', transliteration: 'Ар-Рум', russian: 'Румы', ayahs: 60, type: 'meccan' },
  { number: 31, arabic: 'لقمان', transliteration: 'Лукман', russian: 'Лукман', ayahs: 34, type: 'meccan' },
  { number: 32, arabic: 'السجدة', transliteration: 'Ас-Саджда', russian: 'Поклон', ayahs: 30, type: 'meccan' },
  { number: 33, arabic: 'الأحزاب', transliteration: 'Аль-Ахзаб', russian: 'Союзники', ayahs: 73, type: 'medinan' },
  { number: 34, arabic: 'سبأ', transliteration: 'Саба', russian: 'Саба', ayahs: 54, type: 'meccan' },
  { number: 35, arabic: 'فاطر', transliteration: 'Фатир', russian: 'Творец', ayahs: 45, type: 'meccan' },
  { number: 36, arabic: 'يس', transliteration: 'Ясин', russian: 'Ясин', ayahs: 83, type: 'meccan' },
  { number: 37, arabic: 'الصافات', transliteration: 'Ас-Саффат', russian: 'Выстроившиеся в ряды', ayahs: 182, type: 'meccan' },
  { number: 38, arabic: 'ص', transliteration: 'Сад', russian: 'Сад', ayahs: 88, type: 'meccan' },
  { number: 39, arabic: 'الزمر', transliteration: 'Аз-Зумар', russian: 'Толпы', ayahs: 75, type: 'meccan' },
  { number: 40, arabic: 'غافر', transliteration: 'Гафир', russian: 'Прощающий', ayahs: 85, type: 'meccan' },
  { number: 41, arabic: 'فصلت', transliteration: 'Фуссилят', russian: 'Разъяснённые', ayahs: 54, type: 'meccan' },
  { number: 42, arabic: 'الشورى', transliteration: 'Аш-Шура', russian: 'Совет', ayahs: 53, type: 'meccan' },
  { number: 43, arabic: 'الزخرف', transliteration: 'Аз-Зухруф', russian: 'Украшения', ayahs: 89, type: 'meccan' },
  { number: 44, arabic: 'الدخان', transliteration: 'Ад-Духан', russian: 'Дым', ayahs: 59, type: 'meccan' },
  { number: 45, arabic: 'الجاثية', transliteration: 'Аль-Джасийа', russian: 'Коленопреклонённые', ayahs: 37, type: 'meccan' },
  { number: 46, arabic: 'الأحقاف', transliteration: 'Аль-Ахкаф', russian: 'Барханы', ayahs: 35, type: 'meccan' },
  { number: 47, arabic: 'محمد', transliteration: 'Мухаммад', russian: 'Мухаммад', ayahs: 38, type: 'medinan' },
  { number: 48, arabic: 'الفتح', transliteration: 'Аль-Фатх', russian: 'Победа', ayahs: 29, type: 'medinan' },
  { number: 49, arabic: 'الحجرات', transliteration: 'Аль-Худжурат', russian: 'Комнаты', ayahs: 18, type: 'medinan' },
  { number: 50, arabic: 'ق', transliteration: 'Каф', russian: 'Каф', ayahs: 45, type: 'meccan' },
  { number: 51, arabic: 'الذاريات', transliteration: 'Аз-Зарийат', russian: 'Рассеивающие', ayahs: 60, type: 'meccan' },
  { number: 52, arabic: 'الطور', transliteration: 'Ат-Тур', russian: 'Гора', ayahs: 49, type: 'meccan' },
  { number: 53, arabic: 'النجم', transliteration: 'Ан-Наджм', russian: 'Звезда', ayahs: 62, type: 'meccan' },
  { number: 54, arabic: 'القمر', transliteration: 'Аль-Камар', russian: 'Луна', ayahs: 55, type: 'meccan' },
  { number: 55, arabic: 'الرحمن', transliteration: 'Ар-Рахман', russian: 'Милостивый', ayahs: 78, type: 'medinan' },
  { number: 56, arabic: 'الواقعة', transliteration: 'Аль-Вакыа', russian: 'Неизбежное', ayahs: 96, type: 'meccan' },
  { number: 57, arabic: 'الحديد', transliteration: 'Аль-Хадид', russian: 'Железо', ayahs: 29, type: 'medinan' },
  { number: 58, arabic: 'المجادلة', transliteration: 'Аль-Муджадала', russian: 'Препирающаяся', ayahs: 22, type: 'medinan' },
  { number: 59, arabic: 'الحشر', transliteration: 'Аль-Хашр', russian: 'Сбор', ayahs: 24, type: 'medinan' },
  { number: 60, arabic: 'الممتحنة', transliteration: 'Аль-Мумтахана', russian: 'Испытуемая', ayahs: 13, type: 'medinan' },
  { number: 61, arabic: 'الصف', transliteration: 'Ас-Сафф', russian: 'Ряды', ayahs: 14, type: 'medinan' },
  { number: 62, arabic: 'الجمعة', transliteration: 'Аль-Джумуа', russian: 'Пятница', ayahs: 11, type: 'medinan' },
  { number: 63, arabic: 'المنافقون', transliteration: 'Аль-Мунафикун', russian: 'Лицемеры', ayahs: 11, type: 'medinan' },
  { number: 64, arabic: 'التغابن', transliteration: 'Ат-Тагабун', russian: 'Взаимный обман', ayahs: 18, type: 'medinan' },
  { number: 65, arabic: 'الطلاق', transliteration: 'Ат-Талак', russian: 'Развод', ayahs: 12, type: 'medinan' },
  { number: 66, arabic: 'التحريم', transliteration: 'Ат-Тахрим', russian: 'Запрет', ayahs: 12, type: 'medinan' },
  { number: 67, arabic: 'الملك', transliteration: 'Аль-Мульк', russian: 'Власть', ayahs: 30, type: 'meccan' },
  { number: 68, arabic: 'القلم', transliteration: 'Аль-Калам', russian: 'Перо', ayahs: 52, type: 'meccan' },
  { number: 69, arabic: 'الحاقة', transliteration: 'Аль-Хакка', russian: 'Неминуемое', ayahs: 52, type: 'meccan' },
  { number: 70, arabic: 'المعارج', transliteration: 'Аль-Мааридж', russian: 'Ступени восхождения', ayahs: 44, type: 'meccan' },
  { number: 71, arabic: 'نوح', transliteration: 'Нух', russian: 'Нух', ayahs: 28, type: 'meccan' },
  { number: 72, arabic: 'الجن', transliteration: 'Аль-Джинн', russian: 'Джинны', ayahs: 28, type: 'meccan' },
  { number: 73, arabic: 'المزمل', transliteration: 'Аль-Муззаммиль', russian: 'Закутавшийся', ayahs: 20, type: 'meccan' },
  { number: 74, arabic: 'المدثر', transliteration: 'Аль-Муддассир', russian: 'Завернувшийся', ayahs: 56, type: 'meccan' },
  { number: 75, arabic: 'القيامة', transliteration: 'Аль-Кийама', russian: 'Воскресение', ayahs: 40, type: 'meccan' },
  { number: 76, arabic: 'الإنسان', transliteration: 'Аль-Инсан', russian: 'Человек', ayahs: 31, type: 'medinan' },
  { number: 77, arabic: 'المرسلات', transliteration: 'Аль-Мурсалят', russian: 'Посылаемые', ayahs: 50, type: 'meccan' },
  { number: 78, arabic: 'النبأ', transliteration: 'Ан-Наба', russian: 'Весть', ayahs: 40, type: 'meccan' },
  { number: 79, arabic: 'النازعات', transliteration: 'Ан-Назиат', russian: 'Исторгающие', ayahs: 46, type: 'meccan' },
  { number: 80, arabic: 'عبس', transliteration: 'Абаса', russian: 'Нахмурился', ayahs: 42, type: 'meccan' },
  { number: 81, arabic: 'التكوير', transliteration: 'Ат-Таквир', russian: 'Скручивание', ayahs: 29, type: 'meccan' },
  { number: 82, arabic: 'الانفطار', transliteration: 'Аль-Инфитар', russian: 'Разрывание', ayahs: 19, type: 'meccan' },
  { number: 83, arabic: 'المطففين', transliteration: 'Аль-Мутаффифин', russian: 'Обвешивающие', ayahs: 36, type: 'meccan' },
  { number: 84, arabic: 'الانشقاق', transliteration: 'Аль-Иншикак', russian: 'Расщепление', ayahs: 25, type: 'meccan' },
  { number: 85, arabic: 'البروج', transliteration: 'Аль-Бурудж', russian: 'Созвездия', ayahs: 22, type: 'meccan' },
  { number: 86, arabic: 'الطارق', transliteration: 'Ат-Тарик', russian: 'Ночной путник', ayahs: 17, type: 'meccan' },
  { number: 87, arabic: 'الأعلى', transliteration: 'Аль-Аала', russian: 'Всевышний', ayahs: 19, type: 'meccan' },
  { number: 88, arabic: 'الغاشية', transliteration: 'Аль-Гашийа', russian: 'Покрывающее', ayahs: 26, type: 'meccan' },
  { number: 89, arabic: 'الفجر', transliteration: 'Аль-Фаджр', russian: 'Заря', ayahs: 30, type: 'meccan' },
  { number: 90, arabic: 'البلد', transliteration: 'Аль-Балад', russian: 'Город', ayahs: 20, type: 'meccan' },
  { number: 91, arabic: 'الشمس', transliteration: 'Аш-Шамс', russian: 'Солнце', ayahs: 15, type: 'meccan' },
  { number: 92, arabic: 'الليل', transliteration: 'Аль-Лайль', russian: 'Ночь', ayahs: 21, type: 'meccan' },
  { number: 93, arabic: 'الضحى', transliteration: 'Ад-Духа', russian: 'Утро', ayahs: 11, type: 'meccan' },
  { number: 94, arabic: 'الشرح', transliteration: 'Аш-Шарх', russian: 'Раскрытие', ayahs: 8, type: 'meccan' },
  { number: 95, arabic: 'التين', transliteration: 'Ат-Тин', russian: 'Смоковница', ayahs: 8, type: 'meccan' },
  { number: 96, arabic: 'العلق', transliteration: 'Аль-Алак', russian: 'Сгусток крови', ayahs: 19, type: 'meccan' },
  { number: 97, arabic: 'القدر', transliteration: 'Аль-Кадр', russian: 'Могущество', ayahs: 5, type: 'meccan' },
  { number: 98, arabic: 'البينة', transliteration: 'Аль-Баyyина', russian: 'Ясное знамение', ayahs: 8, type: 'medinan' },
  { number: 99, arabic: 'الزلزلة', transliteration: 'Аз-Зальзаля', russian: 'Землетрясение', ayahs: 8, type: 'medinan' },
  { number: 100, arabic: 'العاديات', transliteration: 'Аль-Адийат', russian: 'Скачущие', ayahs: 11, type: 'meccan' },
  { number: 101, arabic: 'القارعة', transliteration: 'Аль-Кариа', russian: 'Поражающее', ayahs: 11, type: 'meccan' },
  { number: 102, arabic: 'التكاثر', transliteration: 'Ат-Такасур', russian: 'Приумножение', ayahs: 8, type: 'meccan' },
  { number: 103, arabic: 'العصر', transliteration: 'Аль-Аср', russian: 'Время', ayahs: 3, type: 'meccan' },
  { number: 104, arabic: 'الهمزة', transliteration: 'Аль-Хумаза', russian: 'Хулитель', ayahs: 9, type: 'meccan' },
  { number: 105, arabic: 'الفيل', transliteration: 'Аль-Филь', russian: 'Слон', ayahs: 5, type: 'meccan' },
  { number: 106, arabic: 'قريش', transliteration: 'Курайш', russian: 'Курайш', ayahs: 4, type: 'meccan' },
  { number: 107, arabic: 'الماعون', transliteration: 'Аль-Маун', russian: 'Подаяние', ayahs: 7, type: 'meccan' },
  { number: 108, arabic: 'الكوثر', transliteration: 'Аль-Каусар', russian: 'Изобилие', ayahs: 3, type: 'meccan' },
  { number: 109, arabic: 'الكافرون', transliteration: 'Аль-Кафирун', russian: 'Неверующие', ayahs: 6, type: 'meccan' },
  { number: 110, arabic: 'النصر', transliteration: 'Ан-Наср', russian: 'Помощь', ayahs: 3, type: 'medinan' },
  { number: 111, arabic: 'المسد', transliteration: 'Аль-Масад', russian: 'Пальмовые волокна', ayahs: 5, type: 'meccan' },
  { number: 112, arabic: 'الإخلاص', transliteration: 'Аль-Ихлас', russian: 'Искренность', ayahs: 4, type: 'meccan' },
  { number: 113, arabic: 'الفلق', transliteration: 'Аль-Фалак', russian: 'Рассвет', ayahs: 5, type: 'meccan' },
  { number: 114, arabic: 'الناس', transliteration: 'Ан-Нас', russian: 'Люди', ayahs: 6, type: 'meccan' },
];

export const SURAH_BY_NUMBER = Object.fromEntries(SURAHS.map(s => [s.number, s])) as Record<number, SurahMeta>;

export const SURAHS_WITH_CONTENT = new Set([
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
  11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
  21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
  31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
  41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
  51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
  61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
  71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
  81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
  91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
  101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
  111, 112, 113, 114,
]);

/** Suras for which the Alafasy mp3 files are bundled in
 *  `web/public/audio/<globalAyahNum>.mp3`. For these, the player
 *  serves audio from the local origin (instant, no CORS, no UA
 *  throttling); other surahs fall back to cdn.islamic.network.
 *
 *  Keep this list in sync with the actual file inventory under
 *  `web/public/audio/` — bundling more surahs costs ~50 KB per ayah.
 *  Currently shipped: surahs 67-114 (the last 28 short surahs that
 *  the user is most likely to start with).  Add a surah here only
 *  after dropping its mp3s into the directory. */
export const SURAHS_WITH_LOCAL_AUDIO = new Set([
  67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
  81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
  91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
  101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
  111, 112, 113, 114,
]);
